In [ ]:
import os
import csv
import numpy as np
import pandas as pd
import skfuzzy as fuzz
import matplotlib as mpl
from matplotlib import cm
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler


#El csv debe estar en el mismo folder del archivo python
current_dir = os.getcwd()
filename = "incidencia.csv"

dataset_path = os.path.join(current_dir, filename)
df = pd.read_csv(dataset_path)

df.head()

,Unnamed: 0,Provincia,Canton,Madrugada,Mañana,Noche,Tarde,Total,Perc Provincia,Perc Pais,Incidencia
0,0,ALAJUELA,ALAJUELA,1593,1275,1972,1600,6440,42.254445,6.648497,Muy Alta
1,1,ALAJUELA,ATENAS,116,60,104,100,380,2.493275,0.392303,Baja
2,2,ALAJUELA,GRECIA,162,144,240,184,730,4.789712,0.753634,Moderada
3,3,ALAJUELA,GUATUSO,118,64,45,44,271,1.778099,0.279774,Baja
4,4,ALAJUELA,LOS CHILES,135,131,187,159,612,4.015485,0.631814,Moderada

# Normalizacion de Datos en inceidencias.csv
- Usando un MinMax Scaler de Sklearn

In [55]:

# Seleccion de columnas numericas
numeric_columns = ['Madrugada', 'Mañana', 'Tarde', 'Noche', 'Total']

print(numeric_columns)

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Normalizacion de Columnas
normalized_values = scaler.fit_transform(df[numeric_columns])

# Agregar columnas normalizadas al Dataframe
for i, col in enumerate(numeric_columns):
    df[f'{col}_norm'] = normalized_values[:, i]


df.sample(10)

['Madrugada', 'Mañana', 'Tarde', 'Noche', 'Total']

,Unnamed: 0,Provincia,Canton,Madrugada,Mañana,Noche,Tarde,Total,Perc Provincia,Perc Pais,Incidencia,Madrugada_norm,Mañana_norm,Tarde_norm,Noche_norm,Total_norm
41,41,HEREDIA,SAN RAFAEL,144,104,199,154,601,7.331056,0.620458,Moderada,0.024981,0.027194,0.026032,0.033433,0.026712
36,36,HEREDIA,BELEN,125,88,313,129,655,7.989754,0.676206,Moderada,0.021330,0.022708,0.021383,0.053493,0.029438
0,0,ALAJUELA,ALAJUELA,1593,1275,1972,1600,6440,42.254445,6.648497,Muy Alta,0.303420,0.355481,0.294905,0.345416,0.321551
46,46,LIMON,LIMON,621,419,688,548,2276,26.351743,2.349686,Muy Alta,0.116641,0.115503,0.099293,0.119479,0.111291
61,61,PUNTARENAS,PUERTO JIM&#201;NEZ,187,66,65,63,381,3.109443,0.393335,Baja,0.033244,0.016541,0.009111,0.009854,0.015603
65,65,SAN JOSE,ALAJUELITA,332,181,321,230,1064,2.905278,1.098447,Alta,0.061107,0.048780,0.040164,0.054901,0.050091
44,44,HEREDIA,SARAPIQUI,206,151,224,215,796,9.709685,0.821771,Alta,0.036895,0.040370,0.037374,0.037832,0.036558
29,29,GUANACASTE,LA CRUZ,99,79,47,53,278,3.273669,0.287000,Baja,0.016334,0.020185,0.007252,0.006687,0.010402
7,7,ALAJUELA,PALMARES,61,45,87,58,251,1.646874,0.259126,Baja,0.009032,0.010653,0.008181,0.013725,0.009039
63,63,PUNTARENAS,QUEPOS,281,286,347,393,1307,10.666775,1.349315,Alta,0.051307,0.078217,0.070472,0.059476,0.062361